[settings]
audio_path = "~/ezdl/Music"
video_path = "~/ezdl/Videos"
file_naming_scheme = "%(title)s.%(ext)s"
audio_quality = 0
audio_format = "flac"
video_format = "mp4"
download_playlist = false
use_cookies = false
cookie_browser = "brave"
embed_thumbnail = true
embed_metadata = true

[other]
spotify_id = "client_id"
spotify_secret = "client_secret"
